name: CMake (Single Platform)
on: [push, pull_request]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive 

      - name: Install dependencies
        run: |
          sudo apt-get install -y build-essential cmake libhdf5-dev

      - name: Configure CMake
        # continue-on-error: true
        run: |
          cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DMHD=ON

      - name: Build
        # continue-on-error: true
        run: |
          cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Test
        continue-on-error: true
        working-directory: ${{github.workspace}}/build
        run: |
          ctest -C ${{env.BUILD_TYPE}} --output-on-failure || echo "Tests failed but continuing..."
